services:
  # Production optimizations for Next.js Application
  app:
    container_name: video-social-app-prod
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo-db:27017/video_social_prod_db
      - MONGODB_DB=video_social_prod_db
      - REDIS_URL=redis://redis-cache:6379
    # Remove port exposure (access through nginx only)
    ports: []
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Production MongoDB optimizations
  mongo-db:
    container_name: video-social-mongodb-prod
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=video_social_prod_db
    # Remove external port exposure for security
    ports: []
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Production Redis optimizations
  redis-cache:
    container_name: video-social-redis-prod
    restart: always
    # Remove external port exposure for security
    ports: []
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Production Nginx with SSL support
  nginx:
    container_name: video-social-nginx-prod
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'
        reservations:
          memory: 64M
          cpus: '0.1'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"